name: jabber
version: 0.1.0
web:
  compiler:
    debug: dartdevc
dependencies:
dev_dependencies:
  build_runner:
  build_web_compilers:
transformers:
- $dart2js:
    commandLineOptions: [--show-package-warnings]
