name: jabber
version: 0.1.0
web:
  compiler:
    debug: dartdevc
dependencies:
dev_dependencies:
  build_runner:
  build_web_compilers:
transformers:
- $dart2js:
    commandLineOptions: [--show-package-warnings]
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        # These are globs for the entrypoints you want to compile.
        generate_for:
        - test/**.browser_test.dart
        - web/**.dart
        options:
          compiler: dart2js
          # List any dart2js specific args here, or omit it.
          dart2js_args:
          - -O2 --fast-startup --minify --trust-primitives --trust-type-annotations
